version: '3.8'

services:
  sasposts:
    build:
    ports:
      - "8080:8080"
    environment:
      - DB_TYPE=postgres
      - PG_URL=postgres://user:password@db:5432/sasposts?sslmode=disable

      - REDIS_URL=redis:6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sasposts
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: