// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Comment struct {
	ID        string     `json:"id"`
	PostID    string     `json:"postID"`
	ParentID  *string    `json:"parentID,omitempty"`
	Author    string     `json:"author"`
	Content   string     `json:"content"`
	CreatedAt time.Time  `json:"createdAt"`
	Children  []*Comment `json:"children"`
}

type Mutation struct {
}

type NewCommentInput struct {
	PostID   string  `json:"postID"`
	ParentID *string `json:"parentID,omitempty"`
	Author   string  `json:"author"`
	Content  string  `json:"content"`
}

type NewPostInput struct {
	Title         string `json:"title"`
	Content       string `json:"content"`
	Author        string `json:"author"`
	AllowComments bool   `json:"allowComments"`
}

type Post struct {
	ID            string     `json:"id"`
	Title         string     `json:"title"`
	Content       string     `json:"content"`
	Author        string     `json:"author"`
	AllowComments bool       `json:"allowComments"`
	Comments      []*Comment `json:"comments"`
}

type Query struct {
}

type Subscription struct {
}
